name: {{ cookiecutter.project_slug }}
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python >=3.10,<=3.14
  - pip
{%- if cookiecutter.build_system == "poetry" %}
  - poetry
{%- elif cookiecutter.build_system == "flit" %}
  - flit
{%- elif cookiecutter.build_system == "mesonpy" %}
  - meson-python
{%- elif cookiecutter.build_system == "setuptools" %}
  - setuptools
  - python-build
{%- elif cookiecutter.build_system == "pdm" %}
  - pdm
{%- elif cookiecutter.build_system == "hatch" %}
  - hatch
{%- elif cookiecutter.build_system == "maturin" %}
  - maturin
  - rust
{%- elif cookiecutter.build_system == "scikit-build-core" %}
  - scikit-build-core
  - cmake
{%- elif cookiecutter.build_system == "pybind11" %}
  - pybind11
  - cmake
{%- elif cookiecutter.build_system == "pixi" %}
  - setuptools
  - pixi
  - python-build
{%- elif cookiecutter.build_system == "uv" %}
  - uv
  - python-build
{%- endif %}
  - nodejs # used by semantic-release
{%- if cookiecutter.use_shellcheck == "yes" %}
  - shellcheck
{%- endif %}
{%- if cookiecutter.documentation_engine.startswith("sphinx") %}
  - pandoc
{%- endif %}
{%- if cookiecutter.use_make == "yes" %}
  - make
{%- endif %}
{%- if cookiecutter.build_system == "poetry" and cookiecutter.documentation_engine == "mkdocs" %}
  - pip:
      # distlib issue
      - paginate==0.5.6
{%- endif %}
