---
name: ðŸ“  Documentation Report
description: Create a report for problems with the docs
labels: ["docs", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: >
        **Thank you for wanting to report a problem with scicookie's documentation!**


        âš 
        Verify first that your issue is not [already reported on
        GitHub][issue search].


        [issue search]: https://github.com/osl-incubator/scicookie/issues?q=is%3Aopen+is%3Aissue+label%3Adocs

  - type: textarea
    attributes:
      label: Summary
      description: >-
        Explain the problem briefly below, add suggestions to wording or structure.
        If there are external references that are related please link them here
        as well.
      placeholder: >-
        I was reading scicookie's documentation for scicookie version X and I'm having
        problems understanding Y.
        It would be very helpful if that got rephrased as Z.
    validations:
      required: true

  - type: input
    attributes:
      label: Documentation Page Link
      description: |
        Paste the link to the documentation webpage that you have a question on.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: |
        Read [`scicookie's` Code of Conduct][CoC] first.

        [CoC]: https://github.com/osl-incubator/scicookie/blob/main/CODE_OF_CONDUCT.md
      options:
        - label: I agree to follow the Code of Conduct
          required: true
---
This template has been adopted from [pyhf](https://github.com/scikit-hep/pyhf/tree/main/.github/ISSUE_TEMPLATE)'s excellent bug report template.
