{%- if cookiecutter.project_layout == "src" -%}
{%- set package_path = "src/" + cookiecutter.package_slug -%}
{%- else -%}
{%- set package_path = cookiecutter.package_slug -%}
{%- endif -%}
version: 1.0
groups:
  clean:
    targets:
      all:
        help: Clean unnecessary temporary files
        run: |
          rm -fr build/
          rm -fr dist/
          rm -fr .eggs/
          find . -name '*.egg-info' -exec rm -fr {} +
          find . -name '*.egg' -exec rm -f {} +
          find . -name '*.pyc' -exec rm -f {} +
          find . -name
          find . -name '__pycache__' -exec rm -fr '*.pyo' -exec rm -f {} +
          find . -name '*~' -exec rm -f {} +{} +
          rm -f .coverage
          rm -fr htmlcov/
          rm -fr .pytest_cache
          rm -fr .mypy_cache
          rm -fr .ruff_cache

  docs:
    targets:
      build:
        help: Build documentation
        run: |
          {%- if cookiecutter.documentation_engine == "jupyter-book" %}
          rm -rf docs/_build
          jupyter-book build docs
          {%- elif cookiecutter.documentation_engine == "mkdocs" %}
          mkdocs build --config-file mkdocs.yaml
          {%- elif cookiecutter.documentation_engine == "sphinx" %}
          sphinx-apidoc -o docs/_build {{ package_path }}
          {%- endif %}

      preview:
        help: Preview documentation page locally
        dependencies:
          - target: docs.build
        run: |
          {%- if cookiecutter.documentation_engine == "jupyter-book" %}
          cd docs/_build/html/ && python -m http.server
          {%- elif cookiecutter.documentation_engine == "mkdocs" %}
          mkdocs build --config-file mkdocs.yaml
          {%- elif cookiecutter.documentation_engine == "sphinx" %}
          cd docs/_build && python -m http.server
          {%- endif %}

  tests:
    targets:
      linter:
        help: Run linter tools
        run: |
          pre-commit install
          pre-commit run --all-files --verbose

      unit:
        help: run tests
        args:
          path:
            help: Specify the location of the tests
            type: string
            default: ""
          params:
            help: Specify parameters to be used for tests
            type: string
            default: "-vv"
        run: |
          pytest {{ "{{ args.path }} {{ args.params }}" }}

      ci:
        help: run the sames tests executed on CI
        dependencies:
          - target: tests.unit
          - target: tests.linter

  package:
    targets:
      build:
        help: "Build the package"
        run: |
          {%- if cookiecutter.build_system == "poetry" %}
          poetry build
          {%- elif cookiecutter.build_system == "flit" %}
          flit build
          {%- elif cookiecutter.build_system == "mesonpy" %}
          meson build
          {%- elif cookiecutter.build_system == "setuptools" %}
          python -m build
          {%- elif cookiecutter.build_system == "pdm" %}
          pdm build
          {%- elif cookiecutter.build_system == "hatch" %}
          hatch build
          {%- elif cookiecutter.build_system == "maturin" %}
          maturin build
          {%- elif cookiecutter.build_system == "pybind11" %}
          python -m build
          {%- endif %}

  release:
    vars:
      app: |
        npx --yes \
        -p semantic-release \
        -p "@semantic-release/commit-analyzer" \
        -p "@semantic-release/release-notes-generator" \
        -p "@semantic-release/changelog" \
        -p "@semantic-release/exec" \
        -p "@semantic-release/github" \
        -p "@semantic-release/git" \
        -p "@google/semantic-release-replace-plugin" \
        semantic-release

    targets:
      ci:
        help: run semantic release on CI
        run: {{ "{{ vars.app }} --ci" }}

      dry:
        help: run semantic release in dry-run mode
        run: {{ "{{ vars.app }} --dry-run" }}
