name: scicookie
channels:
  - nodefaults
  - conda-forge
dependencies:
  - bash
  - git
  - opensciencelabs::circleci-cli
  - python >=3.10,<3.14
  - poetry >=2
  - nodejs
  - compilers
  - pip
  - pip:
      - makim==1.29.0
      - xonsh>=0.22.8
      - paginate==0.5.6
