name: {{ cookiecutter.project_slug }}
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python <3.11
{%- if cookiecutter.build_system == 'poetry' %}
  - poetry
{%- elif cookiecutter.build_system == 'flit' %}
  - flit
{%- elif cookiecutter.build_system == 'mesonpy' %}
  - meson-python
{%- endif %}
  - nodejs  # used by semantic-release
  - shellcheck
{%- if cookiecutter.documentation_engine == 'sphinx' %}
  - pandoc
{%- endif %}
