name: {{ cookiecutter.project_slug }}
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python <3.11
{%- if cookiecutter.build_system == 'poetry' %}
  - poetry
{%- else %}
  - flit
{%- endif %}
  - nodejs  # used by semantic-release
  - shellcheck
{%- if cookiecutter.documentation_engine == 'sphinx' %}
  - pandoc
{%- endif %}
